name: Deploy on Sandbox ECS
on:
    push:
        branches:
            - trunk
            - develop

jobs:
    build:
        uses: BonusX-Global/bx-all/.github/workflows/build-and-delivery-to-ecs-v02.yml@main
        secrets:
            pat-read-package: ${{ secrets.PAT_TOKEN }}
            aws-access-key-id: ${{secrets.SANDBOX_AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
        with:
            cluster: ${{ vars.SANDBOX_ECS_CLUSTER }}
            service: ${{ vars.SANDBOX_ECS_SERVICE }}
            image-tag: ${{ github.sha }}
            task-definition: ${{ vars.SANDBOX_ECS_TASK_DEFINITION }}
            container-name: ${{ vars.CONTAINER_NAME }}
            aws-region: ${{ vars.AWS_REGION }}
            repository: ${{ vars.SANDBOX_ECR_REPOSITORY }}
