name: Build with docker

env:
  DOCKER_IMAGE_TAG: ${{ github.event.repository.name }}/${{ github.ref_name }}:latest

on:
  workflow_call:
    inputs:
      context:
        required: false
        type: string
        default: .
      bucket-to-merge:
        required: false
        type: string
        default: ""
      docker-cache:
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Docker
        uses: BonusX-Global/bx-all/.github/actions/docker-build@main
        with:
          context: ${{ inputs.context }}
          tags: ${{ env.DOCKER_IMAGE_TAG }}
          docker-cache: ${{ inputs.docker-cache }}