on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow

env:
  DOCKER_IMAGE_TAG: ${{ github.event.repository.name }}/${{ github.ref_name }}:latest

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        push: false
        tags: ${{ env.DOCKER_IMAGE_TAG }}
   

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.2.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


